# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'front' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # ✅ Google Maps SDK 추가
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  # ✅ AirGoogleMaps 추가
  pod 'react-native-google-maps', :path => '../node_modules/react-native-maps', :modular_headers => true

# ✅ react-native-permissions 추가 (권한 요청 관련)
  rnPermissionsPodspecs = [
    'RNPermissions/PERMISSIONS_LOCATION_WHEN_IN_USE', # 📍 위치 권한
    'RNPermissions/PERMISSIONS_CAMERA',              # 📸 카메라 권한
    'RNPermissions/PERMISSIONS_PHOTO_LIBRARY',       # 🖼️ 갤러리 권한
    'RNPermissions/PERMISSIONS_NOTIFICATIONS',       # 🔔 알림 권한
  ]

  rnPermissionsPodspecs.each do |spec|
      pod spec
    end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
